name: multiplatform_manifest

on:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
  workflow_call:

jobs:
  pull_and_bundle:
    runs-on: ubuntu-latest
    steps:
      - name: github_login
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull images
        if:  ( github.actor == github.repository_owner ) 
        run: |
          for branch in dev 720
          do
          for arch in amd64 arm64 armv7 ppc64le
          do
          echo $arch
          docker pull ghcr.io/${{ github.actor }}/nwchem-$branch:$arch || true
          docker manifest create ghcr.io/${{ github.actor }}/nwchem-$branch:latest --amend  ghcr.io/${{ github.actor }}/nwchem-$branch:$arch || true
          done
          docker images
          docker manifest push ghcr.io/${{ github.actor }}/nwchem-$branc
          done
        shell: bash
