name: multiplatform_manifest_dev

on:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  pull_and_bundle:
    runs-on: ubuntu-latest
    steps:
      - name: github_login
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull images
        if:  ( github.actor == github.repository_owner ) 
        run: |
          for arch in amd64 arm64 armv7 ppc64le
          do
          echo $arch
          docker pull ghcr.io/${{ github.actor }}/nwchem-dev/$arch:latest
          docker manifest create ghcr.io/${{ github.actor }}/nwchem-devnew:latest --amend  ghcr.io/${{ github.actor }}/nwchem-dev/$arch:latest
          done
          docker images
          docker manifest push ghcr.io/${{ github.actor }}/nwchem-devnew:latest
        shell: bash
      - name: test multimage
        if:  ( github.actor == github.repository_owner ) 
        run: |
          docker images
          docker pull ghcr.io/${{ github.actor }}/nwchem-devnew:latest
          docker buildx imagetools inspect ghcr.io/${{ github.actor }}/nwchem-devnew:latest
          docker run --rm  --entrypoint '/usr/bin/uname' ghcr.io/${{ github.actor }}/nwchem-devnew:latest  -a
          docker run mplatform/manifest-tool inspect ghcr.io/${{ github.actor }}/nwchem-devnew:latest
      - name: test multimage after rm
        if:  ( github.actor == github.repository_owner ) 
        run: |
          docker images
          docker rmi ghcr.io/${{ github.actor }}/nwchem-devnew || true
          docker rmi ghcr.io/${{ github.actor }}/nwchem-dev/amd64
          docker pull ghcr.io/${{ github.actor }}/nwchem-devnew:latest
          docker buildx imagetools inspect ghcr.io/${{ github.actor }}/nwchem-devnew:latest
          docker run --rm --entrypoint '/usr/bin/uname' ghcr.io/${{ github.actor }}/nwchem-devnew:latest  -a
          docker run mplatform/manifest-tool inspect ghcr.io/${{ github.actor }}/nwchem-devnew:latest
