name: multiplatform_manifest

on:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
  workflow_call:

jobs:
  pull_and_bundle:
    runs-on: ubuntu-latest
    steps:
      - name: github_login
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull images
        if:  ( github.actor == github.repository_owner ) 
        run: |
          set -x
          for branch in dev 720
          do
          manifest_tag=ghcr.io/${{ github.actor }}/nwchem-"$branch":latest
          noarch_tag=ghcr.io/${{ github.actor }}/nwchem-"$branch"
          for arch in amd64 arm64 armv7 ppc64le
          do
          echo $arch
          docker pull $noarch_tag:$arch || true
          docker manifest create $manifest_tag --amend  $noarch_tag:$arch || true
          done
          echo "pushing manifest name" "$manifest_tag"
          docker manifest push $manifest_tag
          docker images
          echo 'inspect manifest of '  $manifest_tag
          docker manifest inspect  $manifest_tag
          done
        shell: bash
      - name: test images
        if:  ( github.actor == github.repository_owner ) 
        run: |
          set -x
          branch=dev
          manifest_tag=ghcr.io/${{ github.actor }}/nwchem-"$branch":latest
          noarch_tag=ghcr.io/${{ github.actor }}/nwchem-"$branch"
          docker manifest rm $manifest_tag || true
          docker rmi "$noarch_tag":latest || true
          docker rmi "$noarch_tag" || true
          for arch in amd64 arm64 armv7 ppc64le
          do
          docker rmi "$noarch_tag":"$arch" ||rue
          done
          docker images
          echo "pulling $manifest_tag"
          docker pull "$manifest_tag"
          docker run --rm --entrypoint=uname  "$manifest_tag" -a
