name: nwchem_docker

on:
  push:
  pull_request:
  release:
  schedule:
    - cron: '59 15 * * FRI'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  changes:
    if: |
      !contains(github.event.head_commit.message, 'ci skip')
    runs-on: ubuntu-22.04
    outputs:
      # Expose matched filters as job 'folders' output variable
      folders: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - name: choose_dockerfile_filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          nwchem-dev: 'nwchem-dev/*'
          builddebs.buster: 'builddebs.buster/*'
    - name: cleanup_nochange
      if: steps.filter.outputs.changes == '[]'
      run: echo "no change detected"
  docker_filter:
    needs: [changes]
    if: |
        (github.event_name != 'workflow_dispatch') && (github.event_name != 'schedule')
    strategy:
        fail-fast: false
        matrix:
          folder: ["${{ fromJSON(needs.changes.outputs.folders) }}", helloworld]
          archs: [linux/amd64, linux/arm64, linux/ppc64le, linux/arm/v7]
          fc: [ gfortran, nvfortran]
          include:
            - {folder: nwchem-dev.xlf, archs: linux/ppc64le, fc: xlf}
          exclude:
            - {folder: helloworld, archs: linux/arm64}
            - {folder: helloworld, archs: linux/ppc64le}
            - {folder: helloworld, archs: linux/arm/v7}
            - {folder: nwchem-dev, archs: linux/ppc64le, fc: nvfortran}
            - {folder: nwchem-dev, archs: linux/arm/v7, fc: nvfortran}
    runs-on: ubuntu-latest
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cache
        id: setup-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
          key: ${{ matrix.folder}}-${{ matrix.fc}}/${{ matrix.archs}}-nwchemdockercache-v018
      - name: Qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: crazymax/binfmt:v6.0.0
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
              image=moby/buildkit:master
      - name: Login to GitHub Container Registry
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Arch
        id: get-arch
        run: |
          echo "::set-output name=arch::$(echo ${{matrix.archs }} | sed 's/linux//'|sed  's/\///g' )"
        shell: bash
      - name: FC tag
        id: fc-tag
        run: |
          if [[ ${{ matrix.fc }} == 'gfortran'  ]]; then 
            echo "::set-output name=fc::"  
          else 
            echo "::set-output name=fc::$(echo -${{matrix.fc }}  )"  
          fi
        shell: bash
      - name: fetch cache
        if: (steps.setup-cache.outputs.cache-hit == 'true') && ( matrix.folder  != 'helloworld' )
        run: |
          cd ${{ matrix.folder }}
          ls -lrta
          if [[ -f ~/cache/libext.tar.bz2 ]]; then \
          echo "libext cache present" ; \
          mkdir -p cache|| true ; \
          rsync -av ~/cache/libext* cache/. ; \
          echo "libext cache fetched" ; \
          ls -l cache/ ; \
          echo "======" ; \
          fi
      - name: docker tag
        id: docker-tag
        run: |
          echo "::set-output name=tag:: ghcr.io/${{ github.actor }}/${{ matrix.folder }}${{ steps.fc-tag.outputs.fc }}/${{ steps.get-arch.outputs.arch }}"
        shell: bash
      - name: build date
        id: build-date
        run: |
          echo "::set-output name=date::$(TZ=America/Los_Angeles date +%Y%m%d_%H%M%S)"
      - uses: haya14busa/action-cond@v1
        id: cache-hit-reporter
        with:
          cond: ${{ steps.setup-cache.outputs.cache-hit != '' }}
          if_true: "Y"
          if_false: "N"
      - name: build_filter
        if: ${{ matrix.folder  != 'helloworld' }}
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.actor == github.repository_owner }}
          context: ${{ matrix.folder }}
          shm-size: 256m
          platforms: ${{ matrix.archs }}
          tags: |
            ${{ steps.docker-tag.outputs.tag }}:latest
            ${{ steps.docker-tag.outputs.tag }}:${{ steps.build-date.outputs.date }}
          build-args: |
            FC=${{ matrix.fc }}
            CACHE_HIT=${{ steps.cache-hit-reporter.outputs.value }}
      - name: load and test image
        if:  ( github.actor == github.repository_owner ) && ( matrix.folder  != 'helloworld' ) && ( matrix.folder  != 'nwchem-dev.xlf' )
        run: |
          sleep 30s
          docker pull ${{ steps.docker-tag.outputs.tag }}
          cd /tmp
          umask u=rwx,g=rwx,o=rwx
          umask -S
          svn export https://github.com/nwchemgit/nwchem/trunk/QA >& svnout.log
          cd QA
          if [[ ${{ matrix.archs }} != 'linux/arm/v7' && ${{ matrix.fc }} != 'nvfortran' ]]; then \
          docker run --shm-size 256m --rm --platform ${{matrix.archs }} \
          -e NWCHEM_EXECUTABLE=/opt/nwchem/bin/nwchem --entrypoint='/opt/nwchem/QA/runtests.mpi.unix' \
          -v `pwd`:/opt/nwchem/QA ${{ steps.docker-tag.outputs.tag }} \
          dft_he2+ ;\
          fi
      - name: store cache
        if:  ( github.actor == github.repository_owner ) && ( matrix.folder  != 'helloworld' )
        run: |
            mkdir -p ~/cache/
            docker run --privileged --user 0 --rm --platform ${{matrix.archs }} \
            --entrypoint='/bin/cp' -v ~/cache:/data \
            ${{ steps.docker-tag.outputs.tag }} \
            -rp /opt/nwchem/src/libext/libext.tar.bz2 /data/.  || true
            ls -Ralrt ~/cache || true
  bundle_images1:
    needs: [docker_filter]
    runs-on: ubuntu_latest
    steps:
      - name: Login to GitHub Container Registry
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull and bundle
        if:  ( github.actor == github.repository_owner ) 
        run: |
          for arch in amd64 arm64 armv7 ppc64le
          do
          echo $arch
          docker pull ghcr.io/${{ github.actor }}/nwchem-dev/$arch:latest
          docker manifest create ghcr.io/${{ github.actor }}/nwchem-dev:latest --amend  ghcr.io/${{ github.actor }}/nwchem-dev/$arch:latest
          done
          docker images
          docker manifest push ghcr.io/${{ github.actor }}/nwchem-dev:latest
        shell: bash

  docker_schedule:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule')
    strategy:
        fail-fast: false
        matrix:
          folder:
            - nwchem-dev
          archs: [linux/amd64, linux/arm64, linux/ppc64le, linux/arm/v7]
          fc: [ gfortran, nvfortran]
          include:
            - {folder: nwchem-dev.xlf, archs: linux/ppc64le, fc: xlf}
          exclude:
            - {folder: nwchem-dev, archs: linux/ppc64le, fc: nvfortran}
            - {folder: nwchem-dev, archs: linux/arm/v7, fc: nvfortran}
    runs-on: ubuntu-latest
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cache
        id: setup-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
          key: ${{ matrix.folder}}-${{ matrix.fc}}/${{ matrix.archs}}-nwchemdockercache-v018
      - name: Qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: crazymax/binfmt:v6.0.0
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
              image=moby/buildkit:master
      - name: Login to GitHub Container Registry
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Arch
        id: get-arch
        run: |
          echo "::set-output name=arch::$(echo ${{matrix.archs }} | sed 's/linux//'|sed  's/\///g' )"
        shell: bash
      - name: FC tag
        id: fc-tag
        run: |
          if [[ ${{ matrix.fc }} == 'gfortran'  ]]; then 
            echo "::set-output name=fc::"  
          else 
            echo "::set-output name=fc::$(echo -${{matrix.fc }}  )"  
          fi
        shell: bash
      - name: fetch cache
        if: (steps.setup-cache.outputs.cache-hit == 'true') && ( matrix.folder  != 'helloworld' )
        run: |
          cd ${{ matrix.folder }}
          ls -lrta
          if [[ -f ~/cache/libext.tar.bz2 ]]; then \
          echo "libext cache present" ; \
          mkdir -p cache|| true ; \
          rsync -av ~/cache/libext* cache/. ; \
          echo "libext cache fetched" ; \
          ls -l cache/ ; \
          echo "======" ; \
          fi
      - name: docker tag
        id: docker-tag
        run: |
          echo "::set-output name=tag:: ghcr.io/${{ github.actor }}/${{ matrix.folder }}${{ steps.fc-tag.outputs.fc }}/${{ steps.get-arch.outputs.arch }}"
        shell: bash
      - name: build date
        id: build-date
        run: |
          echo "::set-output name=date::$(TZ=America/Los_Angeles date +%Y%m%d_%H%M%S)"
      - uses: haya14busa/action-cond@v1
        id: cache-hit-reporter
        with:
          cond: ${{ steps.setup-cache.outputs.cache-hit != '' }}
          if_true: "Y"
          if_false: "N"
      - name: build_schedule
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.actor == github.repository_owner }}
          context: ${{ matrix.folder }}
          shm-size: 256m
          platforms: ${{ matrix.archs }}
          tags: |
            ${{ steps.docker-tag.outputs.tag }}:latest
            ${{ steps.docker-tag.outputs.tag }}:${{ steps.build-date.outputs.date }}
          build-args: |
            FC=${{ matrix.fc }}
            CACHE_HIT=${{ steps.cache-hit-reporter.outputs.value }}
      - name: load and test image
        if:  ( github.actor == github.repository_owner ) && ( matrix.folder  != 'helloworld' ) && ( matrix.folder  != 'nwchem-dev.xlf' )
        run: |
          docker pull ${{ steps.docker-tag.outputs.tag }}
          cd /tmp
          umask u=rwx,g=rwx,o=rwx
          umask -S
          svn export https://github.com/nwchemgit/nwchem/trunk/QA >& svnout.log
          cd QA
          if [[ ${{ matrix.archs }} != 'linux/arm/v7' && ${{ matrix.fc }} != 'nvfortran'  ]]; then \
          docker run --shm-size 256m --rm --platform ${{matrix.archs }} \
          -e NWCHEM_EXECUTABLE=/opt/nwchem/bin/nwchem --entrypoint='/opt/nwchem/QA/runtests.mpi.unix' \
          -v `pwd`:/opt/nwchem/QA ${{ steps.docker-tag.outputs.tag }} \
          dft_he2+ ;\
          fi
      - name: store cache
        if:  ( github.actor == github.repository_owner ) && ( matrix.folder  != 'helloworld' )
        run: |
            mkdir -p ~/cache/
            docker run --privileged --user 0 --rm --platform ${{matrix.archs }} \
            --entrypoint='/bin/cp' -v ~/cache:/data \
            ${{ steps.docker-tag.outputs.tag }} \
            -rp /opt/nwchem/src/libext/libext.tar.bz2 /data/.  || true
            ls -Ralrt ~/cache || true
  bundle_images2:
    needs: [docker_schedule]
    runs-on: ubuntu_latest
    steps:
      - name: Login to GitHub Container Registry
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull and bundle
        if:  ( github.actor == github.repository_owner ) 
        run: |
          for arch in amd64 arm64 armv7 ppc64le
          do
          echo $arch
          docker pull ghcr.io/${{ github.actor }}/nwchem-dev/$arch:latest
          docker manifest create ghcr.io/${{ github.actor }}/nwchem-dev:latest --amend  ghcr.io/${{ github.actor }}/nwchem-dev/$arch:latest
          done
          docker images
          docker manifest push ghcr.io/${{ github.actor }}/nwchem-dev:latest
        shell: bash
