name: nwchem_docker

on:
  push:
  pull_request:
  release:
  schedule:
    - cron: '0 0 * * SUN'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'folders' output variable
      folders: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - name: choose_dockerfile_filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          nwchem-700.fedora.sockets: 'nwchem-700.fedora.sockets/*'
          nwchem-700.mpipr: 'nwchem-700.mpipr/*'
          nwchem-700.amazonlinux.sockets: 'nwchem-700.amazonlinux.sockets/*'
          nwchem-dev: 'nwchem-dev/*'
          builddebs.buster: 'builddebs.buster/*'
    - name: gdb1
      run: |
          echo "s.f.o" "${{ steps.filter.outputs }}"
          echo "s.f.o.c" "${{ steps.filter.outputs.changes }}"
          echo "s.f.o.f" "${{ steps.filter.outputs.folders }}"
    - name: cleanup_nochange
      if: steps.filter.outputs.changes == '[]'
      run: echo "no change detected"
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  docker_filter:
    needs: [changes, init]
    if: |
        (github.event_name != 'workflow_dispatch') && (github.event_name != 'schedule') && (${{ needs.changes.outputs.folders }} != '[]')
    strategy:
        matrix:
          folder: ["${{ fromJSON(needs.changes.outputs.folders) }}", helloworld] 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: gdb22
        run: |
            echo "1matrix folder is" "${{ matrix.folder }}"
            echo "2matrix folder is" ${{ matrix.folder }}
      - name: build_filter
        uses: docker/build-push-action@v2
        with:
          push: (${{ github.actor == github.repository_owner }}) && (${{ matrix.folder }} != 'helloworld')
          context: ${{ matrix.folder }}
          tags: ghcr.io/${{ github.actor }}/${{ matrix.folder }}:latest
  docker_schedule:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule')
    needs: [init]
    strategy:
        matrix:
          fld_schedule: [nwchem-dev, nwchem-700.mpipr]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build_schedule
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.actor == github.repository_owner }}
          context: ${{ matrix.fld_schedule }}
          tags: ghcr.io/${{ github.actor }}/${{ matrix.fld_schedule }}:latest
